In [1]:
# Importing pandas library
import pandas as pd

In [2]:
#Loading the dataset
columns_movies = ['ID', 'Title', 'Genres']
movies = pd.read_csv('movies.dat', sep='::', engine='python', header=None, names=columns_movies)
movies['Genres'] = movies['Genres'].str.replace('|', ', ')
movies['Info'] = movies['Title'] +" " + movies['Genres']
movies

,ID,Title,Genres,Info
0,1,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy","Toy Story (1995) Adventure, Animation, Childre..."
1,2,Jumanji (1995),"Adventure, Children, Fantasy","Jumanji (1995) Adventure, Children, Fantasy"
2,3,Grumpier Old Men (1995),"Comedy, Romance","Grumpier Old Men (1995) Comedy, Romance"
3,4,Waiting to Exhale (1995),"Comedy, Drama, Romance","Waiting to Exhale (1995) Comedy, Drama, Romance"
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II (1995) Comedy
...,...,...,...,...
10676,65088,Bedtime Stories (2008),"Adventure, Children, Comedy","Bedtime Stories (2008) Adventure, Children, Co..."
10677,65091,Manhattan Melodrama (1934),"Crime, Drama, Romance","Manhattan Melodrama (1934) Crime, Drama, Romance"
10678,65126,Choke (2008),"Comedy, Drama","Choke (2008) Comedy, Drama"
10679,65130,Revolutionary Road (2008),"Drama, Romance","Revolutionary Road (2008) Drama, Romance"
10680,65133,Blackadder Back & Forth (1999),Comedy,Blackadder Back & Forth (1999) Comedy

In [3]:
# Extracting the names of Movies and storing it in a list
all_movies_names = movies['Title']
len(all_movies_names)

10681

In [4]:
# # Writing each movie name to a new line in the 'movies.txt' file
with open('movies.txt', 'w', encoding='utf-8') as output_file:
    for movie_name in all_movies_names:
        output_file.write(movie_name + '\n')